version: '3.6'

services:
  quic1:
    image: 'cslev/webtraffic_generator:latest' #latest is amd64/intelx86_64, aarch64 is for ARM 64-bit
    container_name: wtg_1  #rename according to you scenario for easier identification

    volumes:
      #proper timing within the host system
      - '/etc/localtime:/etc/localtime:ro'
      - './container_data/WTG_1/archives/webtraffic_gen/archives:rw'
      #for PCAP files - default they are deleted due to storage concerns - set it below to keep them
      - './container_data/WTG_1/pcap:/webtraffic_gen/pcap:rw'
      #for any additional domain lists, please add yours into ./source/domain_lists and refer to it via QUIC_DOH_DOCKER_DOMAIN_LIST later
      - './source/domain_lists:/webtraffic_gen/domain_lists:ro'

    dns: 1.1.1.1 #Remove this line if third-party DNS is not allowed
    shm_size: '4g'

    environment:
      QUIC_DOH_DOCKER_NAME: 'WTG1'  #should be same as container_name
      QUIC_DOH_DOCKER_RESOLVER: ${R1} # resolver to use (defined in .env file)
      QUIC_DOH_DOCKER_START: '1' #first domain to visit in the domain list
      QUIC_DOH_DOCKER_END: '1000' #last domain to visit in the domain list
      QUIC_DOH_DOCKER_BATCH: '200' #how many domains to visit within a batch (don't change unless you know what you are doing)
      QUIC_DOH_DOCKER_INTF: 'eth0' #change this if your container would not have eth0 as a default interface
      QUIC_DOH_DOCKER_DOMAIN_LIST: '/webtraffic_gen/domain_lists/top-1m_tranco2021.csv' #the relative path inside the container pointing to the list of domains to visit (in Alexa list style: id, domain <-one each line)
      QUIC_DOH_DOCKER_META: 'test_quic_no_doh_1' #any meta info to affix your final output files for easier identification
      QUIC_DOH_DOCKER_WEBPAGE_TIMEOUT: '20' #how many seconds we wait for a website to load before throwing timeout error and skip
      QUIC_DOH_DOCKER_ARCHIVE_PATH: '/webtraffic_gen/archives' #where to store the compressed output. Should be the same as defined by the 'volume'
      QUIC_DOH_DOCKER_USE_QUIC: '1' #set it to 1 to enable Quic or 0 to disable
      QUIC_DOH_DOCKER_KEEP_PCAP: '0' #DEBUG ONLY: pcap files can consume all your free space, Set it to 1 to keep pcap and 0 otherwise
      QUIC_DOH_DOCKER_TSO_ON: '0' #Disabled by default as we don't want the NIC to buffer and concatenate fragmented packets that result in jumbo frames. We want packets not greater than 1500B

    cap_add: #in order to disable offloading if required - does not do any harm if left here as it is
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_RESOURCE

  quic2:
    image: 'cslev/webtraffic_generator:latest' #latest is amd64/intelx86_64, aarch64 is for ARM 64-bit
    container_name: webtraffic_generator_1  #rename according to you scenario for easier identification

    volumes:
      #proper timing within the host system
      - '/etc/localtime:/etc/localtime:ro'
      - './container_data/WTG_2/archives:/webtraffic_gen/archives:rw'
      #for PCAP files - default they are deleted due to storage concerns - set it below to keep them
      - './container_data/WTG_2/pcap:/webtraffic_gen/pcap:rw'
      #for any additional domain lists, please add yours into ./source/domain_lists and refer to it via QUIC_DOH_DOCKER_DOMAIN_LIST later
      - './source/domain_lists:/webtraffic_gen/domain_lists:ro'

    dns: 1.1.1.1 #Remove this line if third-party DNS is not allowed
    shm_size: '4g'

    environment:
      QUIC_DOH_DOCKER_NAME: 'WTG_2'  #should be same as container_name
      QUIC_DOH_DOCKER_RESOLVER: ${R1} # resolver to use (defined in .env file)
      QUIC_DOH_DOCKER_START: '1' #first domain to visit in the domain list
      QUIC_DOH_DOCKER_END: '1000' #last domain to visit in the domain list
      QUIC_DOH_DOCKER_BATCH: '200' #how many domains to visit within a batch (don't change unless you know what you are doing)
      QUIC_DOH_DOCKER_INTF: 'eth0' #change this if your container would not have eth0 as a default interface
      QUIC_DOH_DOCKER_DOMAIN_LIST: '/webtraffic_gen/domain_lists/top-1m_tranco2021.csv' #the relative path inside the container pointing to the list of domains to visit (in Alexa list style: id, domain <-one each line)
      QUIC_DOH_DOCKER_META: 'test_quic_no_doh_2' #any meta info to affix your final output files for easier identification
      QUIC_DOH_DOCKER_WEBPAGE_TIMEOUT: '20' #how many seconds we wait for a website to load before throwing timeout error and skip
      QUIC_DOH_DOCKER_ARCHIVE_PATH: '/webtraffic_gen/archives' #where to store the compressed output. Should be the same as defined by the 'volume'
      QUIC_DOH_DOCKER_USE_QUIC: '1' #set it to 1 to enable Quic or 0 to disable
      QUIC_DOH_DOCKER_KEEP_PCAP: '0' #DEBUG ONLY: pcap files can consume all your free space, Set it to 1 to keep pcap and 0 otherwise
      QUIC_DOH_DOCKER_TSO_ON: '0' #Disabled by default as we don't want the NIC to buffer and concatenate fragmented packets that result in jumbo frames. We want packets not greater than 1500B

    cap_add: #in order to disable offloading if required - does not do any harm if left here as it is
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_RESOURCE

